[project]
name = "geoip-starlette-middleware"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Matteo Campinoti", email = "matteo.campinoti94@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "geoip2>=5.3.0",
    "starlette>=1.7.0",
]
